(()=>{const CFG={apiKey:"AIzaSyDD5o-yg5LDfvNuG8eyNh-WdH-GCSCRmYY",authDomain:"vidyarthi---manch.firebaseapp.com",projectId:"vidyarthi---manch",appId:"1:455378425843:web:1e2b594c03d966d7e92486"};
const LOGO='https://i.ibb.co/SDR0DXqb/ei-1764843850590-removebg-preview.png',MN='जानेवारी फेब्रुवारी मार्च एप्रिल मे जून जुलै ऑगस्ट सप्टेंबर ऑक्टोबर नोव्हेंबर डिसेंबर'.split(' ');
const E=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fd=d=>{const[y,m,x]=d.split('-').map(Number);return x+' '+MN[m-1]+' '+y};
const ld=s=>new Promise((ok,no)=>{const e=document.createElement('script');e.src=s;e.onload=ok;e.onerror=no;document.head.appendChild(e)});
let P;const all=()=>P||(P=(async()=>{const b='https://www.gstatic.com/firebasejs/10.12.2/';await ld(b+'firebase-app-compat.js');await ld(b+'firebase-firestore-compat.js');if(!firebase.apps.length)firebase.initializeApp(CFG);
const s=await firebase.firestore().collection('press_releases').where('status','==','published').get();return s.docs.map(d=>d.data()).filter(r=>r.slug&&r.date).sort((a,b)=>b.date.localeCompare(a.date))})());
const link=r=>'press-release.html?s='+encodeURIComponent(r.slug);
const card=r=>`<article class="card" data-slug="${E(r.slug)}" data-t="${E(((r.title||'')+' '+(r.excerpt||'')+' '+(r.tags||[]).join(' ')).toLowerCase())}" data-c="${E(r.category)}" data-y="${r.date.slice(0,4)}" data-m="${r.date.slice(5,7)}" data-d="${r.date}"><img src="${E(r.featuredImage||LOGO)}" alt="${E(r.title)}" loading="lazy"><div class="b"><div><span class="cat">${E(r.category)}</span></div><div class="meta"><time datetime="${r.date}">${fd(r.date)}</time></div><h3><a href="${link(r)}" style="text-decoration:none;color:inherit">${E(r.title)}</a></h3><p>${E(r.excerpt)}</p><a class="btn" href="${link(r)}" style="align-self:flex-start;margin-top:auto">संपूर्ण प्रसिद्धीपत्रक वाचा →</a></div></article>`;
// homepage: merge live cards with static ones, keep newest 4
const merge=async(grid,n)=>{const rs=await all(),have=new Set([...grid.querySelectorAll('.card')].map(e=>e.dataset.slug)),t=document.createElement('div');t.innerHTML=rs.filter(r=>!have.has(r.slug)).map(card).join('');if(!t.children.length)return;
const els=[...grid.querySelectorAll('.card'),...t.children].sort((a,b)=>b.dataset.d.localeCompare(a.dataset.d)).slice(0,n);grid.innerHTML='';els.forEach((e,i)=>{e.classList.toggle('feat',i==0);e.querySelectorAll('.badge').forEach(x=>x.remove());if(i==0)e.querySelector('.cat').insertAdjacentHTML('afterend','<span class="badge">नवीन</span>');grid.appendChild(e)})};
window.PL={all,card,merge,E,fd,LOGO,link};
const g=document.querySelector('#press .grid');if(g&&'IntersectionObserver'in window){new IntersectionObserver((x,o)=>{if(x[0].isIntersecting){o.disconnect();merge(g,4).catch(()=>{})}},{rootMargin:'500px'}).observe(document.getElementById('press'))}})();
